---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.SNIPEIT_NAME}}
  name: {{.SNIPEIT_NAME}}-service
spec:
  ports:
    - name: https
      port: 443
      targetPort: 10443
  selector:
    app: {{.SNIPEIT_NAME}}
